config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :browser_games, only: [:create, :destroy, :new, :edit, :update]

  root 'pages#home'

  match '/help', to: 'pages#help', via: 'get'

  match '/about', to: 'pages#about', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'

  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/browser_game.rb
class BrowserGame < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true 
  validates :name, presence: true, length: { maximum: 50 }
  validates :amount_of_steps, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true, length: { is: 100 }
  validate :content_of_status
  def content_of_status
    if status == nil
      return
    end
    status.chars.each do |s|
      if s != '0' && s != '1' 
        errors.add(:status, "is invalid")
        return
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :browser_games, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: {  maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 4 }
  has_secure_password
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/browser_games_controller.rb
class BrowserGamesController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: [:edit, :destroy, :update]
  
  def new
    @browser_game = current_user.browser_games.build
  end

  def edit
  end
  
  def update
    if @browser_game.update_attributes(parameters)
      redirect_to edit_browser_game_path(@browser_game)
    else
      render 'edit'
    end
  end

  def create
    @browser_game = current_user.browser_games.build(parameters)
    if @browser_game.save
      flash[:success] = "New game created"
      redirect_to edit_browser_game_path(@browser_game)
    else
      render 'new'
    end
  end

  def destroy
    @browser_game.destroy
    redirect_to user_url(current_user)
  end

  private

  def parameters
    params.require(:browser_game).permit(:name, :status, :amount_of_steps)
  end

  def correct_user
    @browser_game = current_user.browser_games.find_by(id: params[:id])
    redirect_to user_url(current_user) if @browser_game.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     sign_in user
     redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to The Game of Life"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @browser_games = @user.browser_games.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User has been deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                  :password_confirmation, :avatar)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "The Game of Life"
  def config_title(title)
    if title.empty?
      BASE_TITLE
    else
      "#{BASE_TITLE} | #{title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token) 
  end
  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/browser_games/edit.html.erb
<% provide(:title, "#{current_user.name} | #{@browser_game.name}") %>
<div class="back-link">
  <%= link_to "Back", user_path(current_user) %>
</div>
<h1><%= @browser_game.name %></h1>
<div class="field">
  <%= form_for(@browser_game) do |f|%>
    <%= f.hidden_field :status, id: "status" %>
    <%= f.hidden_field :amount_of_steps, id: "amount-of-steps" %>
    <canvas id="field">
    </canvas>
    <script>
var NUMBER_OF_COLUMNS = 10;
var NUMBER_OF_ROWS = 10;
var SIZE_OF_CELL = 40;
var WIDTH_OF_BORDER = 5;
var stringWithStates = new String("<%= @browser_game.status %>");
var field = document.getElementById("field"),
  ctx = field.getContext('2d');
var number_of_steps = document.getElementById("amount-of-steps");
var s = document.getElementById("status");
var field_with_amount_of_steps = document.getElementById("field-with-amount-of-steps");
var arrayOfGenerations = new Array();
function evolve() {
  field_with_amount_of_steps = document.getElementById("field-with-amount-of-steps");
  evolveCellGeneration();
  drawGrid();
  var amount = parseInt(number_of_steps.value); 
  number_of_steps.value = (amount + 1).toString();
  field_with_amount_of_steps.innerText = "Amount of steps: "
                                       + number_of_steps.value + ".";
}

function drawGrid() {
  field.width = NUMBER_OF_COLUMNS * (SIZE_OF_CELL + WIDTH_OF_BORDER)
    + WIDTH_OF_BORDER;
  field.height = NUMBER_OF_ROWS * (SIZE_OF_CELL + WIDTH_OF_BORDER)
    + WIDTH_OF_BORDER;
  var grad = ctx.createLinearGradient(0, 0, field.width, field.height);
  grad.addColorStop(0.0, 'black');
  grad.addColorStop(1.0, 'gray');
  ctx.strokeStyle = grad;
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, field.width, field.height);
  var isAlive = false;
  var x, y;
  for (i = 0; i < NUMBER_OF_ROWS; ++i) {
    for (j = 0; j < NUMBER_OF_COLUMNS; ++j) {
      x = j * (SIZE_OF_CELL + WIDTH_OF_BORDER) + WIDTH_OF_BORDER;
      y = i * (SIZE_OF_CELL + WIDTH_OF_BORDER) + WIDTH_OF_BORDER;
      if (stringWithStates.charAt(i * NUMBER_OF_ROWS + j) == '1') {
        isAlive = true;
      }
      else {
        isAlive = false;
      }
      drawCell(x, y, isAlive);
    }
  }
}

function drawCell(coordXOfCell, coordYOfCell, isAlive) {
  if (isAlive) {
    ctx.fillStyle = 'yellow';
  }
  else {
    ctx.fillStyle = 'white';
  }
  ctx.fillRect(coordXOfCell, coordYOfCell, SIZE_OF_CELL, SIZE_OF_CELL);
}

function evolveCellGeneration() {
  arrayOfGenerations.push(stringWithStates);
  tempStringWithStates = stringWithStates;
  var position, state;
  for(i = 0; i < NUMBER_OF_ROWS; ++i) {
    for (j = 0; j < NUMBER_OF_COLUMNS; ++j) {
      position = i * NUMBER_OF_ROWS + j;
      state = tempStringWithStates.charAt(position);
      var numberOfAliveNeighbors = countNumberOfAliveNeighbors(tempStringWithStates, i, j);
      if (state == '1' && !(numberOfAliveNeighbors == 2 || numberOfAliveNeighbors == 3))
      {
        stringWithStates = stringWithStates.slice(0, position) + "0" + stringWithStates.slice(position + 1,  stringWithStates.length);
      }
      if (state == '0' && numberOfAliveNeighbors == 3)
      {
          stringWithStates = stringWithStates.slice(0, position) + "1" + stringWithStates.slice(position + 1, stringWithStates.length);
      }
    }
  }
  s.value = stringWithStates;
}

function returnBack() {
  if (arrayOfGenerations.length == 0) {
    return;
  }
  stringWithStates = arrayOfGenerations.pop();
  s.value = stringWithStates;
  drawGrid();
  var amount = parseInt(number_of_steps.value); 
  number_of_steps.value = (amount - 1).toString();
  field_with_amount_of_steps.innerText = "Amount of steps: "
                                       + number_of_steps.value + ".";
}

function countNumberOfAliveNeighbors(s, numberOfRow, numberOfColumn) {
  var numberOfAliveNeighbors = 0;
  for (t = numberOfRow - 1; t <= numberOfRow + 1; ++t) {
    for (k = numberOfColumn - 1; k <= numberOfColumn + 1; ++k) {
      if (t == numberOfRow && k == numberOfColumn)
        continue;
      var currentRow = t;
      var currentColumn = k;
      if (t < 0) {
        currentRow = NUMBER_OF_ROWS - 1;
      }
      if (t > NUMBER_OF_ROWS - 1) {
        currentRow = 0;
      }
      if (k < 0) {
        currentColumn = NUMBER_OF_COLUMNS - 1;
      }
      if (k > NUMBER_OF_COLUMNS - 1) {
        currentColumn = 0;
      }
      if (s.charAt(currentRow * NUMBER_OF_ROWS + currentColumn) == '1') {
        ++numberOfAliveNeighbors;
      }
    }
  }
  return numberOfAliveNeighbors;
}
drawGrid();
    </script>
    <p id="field-with-amount-of-steps">Amount of steps: <%= @browser_game.amount_of_steps %>.</p>
    <%= f.submit "Save changes" %>
  <% end %>
  <button onclick="evolve();">Next step</button>
  <button onclick="returnBack();">Previous step</button>
</div>

app/views/browser_games/new.html.erb
<% provide(:title, "#{current_user.name} | #{"Create new game"}")%>
<div class="back-link">
  <%= link_to "Back", user_path(current_user) %>
</div>
<h1>Create new game</h1>
<div class="row">
  <div class="container center-block offset3">
    <%= form_for(@browser_game, html: { autocomplete: "off" }) do |f|%>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name%>
      <%= f.hidden_field :status, id: "status" %>
      <%= f.hidden_field :amount_of_steps, id: "amount_of_steps" %>
      <div class="field">
        <canvas id="field">
        </canvas>
      </div>
      <script>
var NUMBER_OF_COLUMNS = 10;
var NUMBER_OF_ROWS = 10;
var SIZE_OF_CELL = 40;
var WIDTH_OF_BORDER = 5;
var field = document.getElementById("field"),
  ctx = field.getContext('2d');
var s = document.getElementById("status");
var stringWithStates = new String("<%= '0' * 100 %>");
function drawGrid() {
  field.width = NUMBER_OF_COLUMNS * (SIZE_OF_CELL + WIDTH_OF_BORDER)
    + WIDTH_OF_BORDER;
  field.height = NUMBER_OF_ROWS * (SIZE_OF_CELL + WIDTH_OF_BORDER)
    + WIDTH_OF_BORDER;
  var grad = ctx.createLinearGradient(0, 0, field.width, field.height);
  grad.addColorStop(0.0, 'black');
  grad.addColorStop(1.0, 'gray');
  ctx.strokeStyle = grad;
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, field.width, field.height);
  var isAlive = false;
  var x, y;
  for (i = 0; i < NUMBER_OF_ROWS; ++i) {
    for (j = 0; j < NUMBER_OF_COLUMNS; ++j) {
      x = j * (SIZE_OF_CELL + WIDTH_OF_BORDER) + WIDTH_OF_BORDER;
      y = i * (SIZE_OF_CELL + WIDTH_OF_BORDER) + WIDTH_OF_BORDER;
      if (stringWithStates.charAt(i * NUMBER_OF_ROWS + j) == '1') {
        isAlive = true;
      }
      else {
        isAlive = false;
      }
      drawCell(x, y, isAlive);
    }
  }
}

function drawCell(coordXOfCell, coordYOfCell, isAlive) {
  if (isAlive) {
    ctx.fillStyle = 'yellow';
  }
  else {
    ctx.fillStyle = 'white';
  }
  ctx.fillRect(coordXOfCell, coordYOfCell, SIZE_OF_CELL, SIZE_OF_CELL);
}

field.addEventListener("mousedown", drawCellWithChanges, false);

function drawCellWithChanges(event) {
  var x = event.pageX;
  var y = event.pageY;
  x -= field.offsetLeft;
  y -= field.offsetTop;
  var i = Math.floor(y / (SIZE_OF_CELL + WIDTH_OF_BORDER));
  var j = Math.floor(x / (SIZE_OF_CELL + WIDTH_OF_BORDER));
  if (i == NUMBER_OF_ROWS) {
    --i;
  }
  if(j == NUMBER_OF_COLUMNS) {
    --j;
  }
  coordX = j * (SIZE_OF_CELL + WIDTH_OF_BORDER) + WIDTH_OF_BORDER;
  coordY = i * (SIZE_OF_CELL + WIDTH_OF_BORDER) + WIDTH_OF_BORDER;
  var index = i * NUMBER_OF_ROWS + j;
  var isAlive = false;
  if (stringWithStates.charAt(index) == '0') {
    stringWithStates = stringWithStates.slice(0, index) + "1"
                     + stringWithStates.slice(index + 1,
                                              NUMBER_OF_ROWS *
                                              NUMBER_OF_COLUMNS);
    isAlive = true;
  }
  else {
    stringWithStates = stringWithStates.slice(0, index) +"0"
                     + stringWithStates.slice(index + 1, 
                                              NUMBER_OF_ROWS * 
                                              NUMBER_OF_COLUMNS);
    isAlive = false;
  }
  s.value = stringWithStates;
  drawCell(coordX, coordY, isAlive);
}
drawGrid();
      </script>
      <%= f.submit "Create new game" %>
    <% end%>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>by Artem</div>
  <nav>
    <ul>
      <li><%= link_to "About Us", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <div id="logo">The Game Of Life</div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li class="active"><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help",  help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= config_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |k, v| %>
      <div class="alert alert-<%= k %>"><%= v %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<%= provide(:title, 'About') %>
<div class="jumbotron">
  <div class="center container">
    <h1>About Us</h1>
    <p>This project contains an implementation of the well-known John Conway's Game of Life</p>
  </div>
</div>

app/views/pages/help.html.erb
<% provide(:title, 'Help')%>
<div class="jumbotron">
  <div class="center container">
    <h1>The Game of Life</h1>
    <p>
The Game of Life is a cellular automaton devised by the British mathematician John Horton Conway in 1970.
    </p>
  </div>
</div>
<a href="http://en.wikipedia.org/wiki/Conway%27s_Game_of_Life">For more information</a>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="center container">
    <h1>Welcome to The Game of Life</h1>
    <p>This is the home page for <%= link_to "The Game of Life", help_path %></p>
    <%= link_to "Sign up now" , signup_path, class: "btn btn-large btn-primary" %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">The form contains <%= pluralize(object.errors.count, "error") %>.</div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update user</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user, html: { autocomplete: "off" }) do |f|%>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name%>
      <%= f.text_field :name%>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                                      data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="container center-block span6 offset3">
  <%= form_for(@user, html: { multipart: true, autocomplete: "off" }) do |f|%>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name%>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-sm-3 col-md-2 sidebar">
    <section>
      <h1>
        <p><%= gravatar_for @user %><p>
        <p><%= @user.name %></p>
      </h1>
    </section>
  </aside>
  <div class="col-md-4">
    <% if current_user?(@user) %>
      <h3>
        <%= link_to "Create new game", new_browser_game_path %>
      </h3>
    <% end %>
    <% if @user.browser_games.any? %>
      <h3>Games (<%= @user.browser_games.count %>)</h3>
      <ul class="browser-games">
        <% @browser_games.each do |game| %>
          <li>
            <span class="content"><%= game.name %></span>
            <% if current_user?(@user) %>
              <span class="span-with-link"><%= link_to "Play" , edit_browser_game_path(game) %></span>
              <span class="span-with-link"><%= link_to "Delete", game, method: :delete,
                                          data: { confirm: "Are you sure?" },
                                          title: game.name %></span><br>
            <% end %>
            <span class="timestamp">
              Created <%= time_ago_in_words(game.created_at) %> ago.
            </span>
          </li>
        <% end %>
      </ul>
      <%= will_paginate @browser_games %>
    <% end %>
  </div>
</div>